/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingPageIndexRouteImport } from './routes/_landing-page/index'

const LandingPageIndexRoute = LandingPageIndexRouteImport.update({
  id: '/_landing-page/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingPageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingPageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing-page/': typeof LandingPageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_landing-page/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingPageIndexRoute: typeof LandingPageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing-page/': {
      id: '/_landing-page/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LandingPageIndexRoute: LandingPageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
